name: 🚀 Release & Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  auto-version:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: 📈 Auto Version Bump
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Version bump
        npm version ${{ github.event.inputs.version_type }} --no-git-tag-version
        VERSION=$(node -p "require('./package.json').version")
        
        # Commit and tag
        git add package.json
        git commit -m "chore: release v$VERSION"
        git tag "v$VERSION"
        
        # Push
        git push origin main
        git push origin "v$VERSION"
        
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        
    outputs:
      version: ${{ env.VERSION }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: [auto-version]
    if: always() && (startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Run tests
      run: npm run build
      
    - name: Verify build artifacts
      run: |
        test -f dist/index.js
        test -f dist/index.d.ts
        test -f banner.png
        test -f logo.png
        
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          🚀 **Streaming Pipeline Core** ${{ github.ref }}
          
          🌊 Memory-Efficient Circular Buffer System
          
          ### Changes
          - See [CHANGELOG.md](CHANGELOG.md) for detailed changes
          
          ### Installation
          ```bash
          npm install @codechu/streaming-pipeline-core
          ```
          
          Built with ❤️ by [Codechu](https://codechu.com)
        draft: false
        prerelease: false